"""
REPL Registry Management

Manages the registry of connected Julia REPL sessions and MCP client sessions.
Integrates with Database and Dashboard modules for logging and monitoring.

This module defines the core data structures and functions for tracking active
REPL connections, their status, and associated metadata. It also manages MCP
client sessions that connect to the proxy.
"""

# ============================================================================
# Data Structures
# ============================================================================

"""
    REPLConnection

Represents a connected Julia REPL session.

# Fields
- `uuid::String`: Unique identifier (UUID) for this session
- `name::String`: Logical name (project name, agent name)
- `port::Int`: REPL's MCP server port
- `pid::Union{Int,Nothing}`: REPL process ID
- `status::Symbol`: Connection status (:ready, :disconnected, :reconnecting, :stopped)
- `created_at::DateTime`: When this session was first created (persists across reconnections)
- `last_heartbeat::DateTime`: Last time we heard from this REPL
- `metadata::Dict{String,Any}`: Additional info (project path, etc.)
- `last_error::Union{String,Nothing}`: Last error message if any
- `missed_heartbeats::Int`: Counter for consecutive missed heartbeats
- `pending_requests::Vector{Tuple{Dict,HTTP.Stream}}`: Buffered requests during reconnection
- `disconnect_time::Union{DateTime,Nothing}`: When REPL disconnected
"""
mutable struct JuliaSession
    uuid::String
    name::String
    port::Int
    pid::Union{Int,Nothing}
    status::Symbol
    created_at::DateTime
    last_heartbeat::DateTime
    metadata::Dict{String,Any}
    last_error::Union{String,Nothing}
    missed_heartbeats::Int
    pending_requests::Vector{Tuple{Dict,HTTP.Stream}}
    disconnect_time::Union{DateTime,Nothing}
end

# ============================================================================
# Global Registries
# ============================================================================

# Julia session registry - tracks all connected Julia sessions
# Note: These are initialized in the parent Proxy module's __init__() function
# to avoid precompilation issues with Dict and ReentrantLock
JULIA_SESSION_REGISTRY = Dict{String,JuliaSession}()  # UUID -> JuliaSession
JULIA_SESSION_REGISTRY_LOCK = ReentrantLock()

# MCP session registry - tracks all connected MCP clients
MCP_SESSION_REGISTRY = Dict{String,MCPSession}()
MCP_SESSION_LOCK = ReentrantLock()

# ============================================================================
# REPL Registration Functions
# ============================================================================

"""
    register_julia_session(uuid::String, name::String, port::Int; pid=nothing, metadata=Dict()) -> (Bool, Union{String,Nothing})

Register a Julia session with the proxy server.

This function:
1. Validates parameters (using validation module)
2. Creates/updates JuliaSession in registry
3. Logs to database (Julia session + event)
4. Logs to dashboard
5. Flushes any pending requests
6. Notifies MCP clients of tool changes

# Arguments
- `uuid::String`: Unique identifier (UUID) for this session (generated by the session itself)
- `name::String`: Logical name for this Julia session (project name, agent name)
- `port::Int`: Port where the Session's MCP server is listening
- `pid::Union{Int,Nothing}=nothing`: Process ID of the Julia session
- `metadata::Dict=Dict()`: Additional metadata (project path, etc.)

# Returns
- `(true, nothing)` on success
- `(false, error_message)` on validation failure

# Example
```julia
success, error = register_julia_session("550e8400-e29b-41d4-a716-446655440000", "my-project", 8080; pid=12345)
if success
    println("Julia session registered successfully")
end
```
"""
function register_julia_session(
    uuid::String,
    name::String,
    port::Int;
    pid::Union{Int,Nothing} = nothing,
    metadata::Dict = Dict(),
)
    # This function needs validate_registration_params, flush_pending_requests,
    # notify_tools_list_changed, log_db_event from parent scope
    # Will be defined when included into proxy.jl

    # Validate input parameters
    valid, error_msg = validate_registration_params(name, port, pid)
    if !valid
        @warn "REPL registration validation failed" uuid = uuid name = name port = port pid =
            pid error = error_msg
        return (false, error_msg)
    end

    # Check for pending requests and copy them outside the lock
    pending = lock(JULIA_SESSION_REGISTRY_LOCK) do
        # Check if this is a re-registration (reconnection) by UUID
        existing_session = get(JULIA_SESSION_REGISTRY, uuid, nothing)
        is_reconnection = existing_session !== nothing

        created_at_time = is_reconnection ? existing_session.created_at : now()
        pending_requests =
            is_reconnection ? existing_session.pending_requests : Tuple{Dict,HTTP.Stream}[]

        if is_reconnection
            @info "Julia session re-registering" uuid = uuid name = name port = port pid =
                pid
            if !isempty(pending_requests)
                @info "Julia session has buffered requests" uuid = uuid name = name buffer_size =
                    length(pending_requests)
            end
        else
            @info "Julia session registering (new)" uuid = uuid name = name port = port pid =
                pid
        end

        # Create/update session
        JULIA_SESSION_REGISTRY[uuid] = JuliaSession(
            uuid,
            name,
            port,
            pid,
            :ready,
            created_at_time,
            now(),  # last_heartbeat
            metadata,
            nothing,
            0,
            Tuple{Dict,HTTP.Stream}[],  # Start with empty buffer
            nothing,
        )

        # Register Julia session in database
        try
            Database.register_julia_session!(
                uuid,
                name,
                "ready";
                port = port,
                pid = pid,
                metadata = metadata,
            )
            log_db_event(
                "julia_session.registered",
                Dict("port" => port, "pid" => pid, "metadata" => metadata, "name" => name);
                julia_session_id = uuid,
            )
        catch e
            @warn "Failed to register session in database" name = name uuid = uuid exception =
                (e, catch_backtrace())
            # Don't fail registration if database logging fails
        end

        # Log registration event to dashboard
        Dashboard.log_event(
            uuid,
            Dashboard.AGENT_START,
            Dict("port" => port, "pid" => pid, "metadata" => metadata, "name" => name),
        )

        # Return pending requests to process outside the lock
        pending_requests
    end

    # If there were pending requests, flush them to the newly connected REPL
    # Do this outside the lock to avoid holding it during HTTP requests
    if !isempty(pending)
        @async flush_pending_requests(uuid, pending)
    end

    # Notify all connected MCP clients that tools list has changed
    notify_tools_list_changed()

    return (true, nothing)
end

"""
    unregister_julia_session(uuid::String)

Remove a Julia session from the proxy registry by UUID.

Logs the unregistration to both database and dashboard.
"""
function unregister_julia_session(uuid::String)
    lock(JULIA_SESSION_REGISTRY_LOCK) do
        if haskey(JULIA_SESSION_REGISTRY, uuid)
            session = JULIA_SESSION_REGISTRY[uuid]
            delete!(JULIA_SESSION_REGISTRY, uuid)

            # Log stop event to dashboard
            Dashboard.log_event(uuid, Dashboard.AGENT_STOP, Dict("name" => session.name))

            # Log unregistration to database
            log_db_event(
                "julia_session.unregistered",
                Dict(
                    "name" => session.name,
                    "port" => session.port,
                    "pid" => session.pid,
                    "status" => string(session.status),
                );
                julia_session_id = uuid,
            )

            @info "Julia session unregistered from proxy" uuid = uuid name = session.name
        end
    end
end

"""
    get_julia_session(uuid::String) -> Union{JuliaSession, Nothing}

Get a Julia session by UUID. Thread-safe.
"""
function get_julia_session(uuid::String)
    lock(JULIA_SESSION_REGISTRY_LOCK) do
        get(JULIA_SESSION_REGISTRY, uuid, nothing)
    end
end

"""
    get_julia_session_by_name(name::String) -> Union{JuliaSession, Nothing}

Get a Julia session by logical name. Thread-safe.
Iterates through all sessions to find a matching name.
"""
function get_julia_session_by_name(name::String)
    lock(JULIA_SESSION_REGISTRY_LOCK) do
        for session in values(JULIA_SESSION_REGISTRY)
            if session.name == name
                return session
            end
        end
        return nothing
    end
end

"""
    list_julia_sessions() -> Vector{JuliaSession}

List all registered Julia sessions. Thread-safe.
"""
function list_julia_sessions()
    lock(JULIA_SESSION_REGISTRY_LOCK) do
        collect(values(JULIA_SESSION_REGISTRY))
    end
end

"""
    update_julia_session_status(uuid::String, status::Symbol; error=nothing)

Update the status of a registered Julia session by UUID, optionally storing error information.

When status changes to :ready, automatically processes any pending requests.
"""
function update_julia_session_status(
    uuid::String,
    status::Symbol;
    error::Union{String,Nothing} = nothing,
)
    lock(JULIA_SESSION_REGISTRY_LOCK) do
        if haskey(JULIA_SESSION_REGISTRY, uuid)
            session = JULIA_SESSION_REGISTRY[uuid]
            session.status = status
            session.last_heartbeat = now()
            if error !== nothing
                session.last_error = error
                session.missed_heartbeats += 1
            elseif status == :ready
                # Clear error and reset counter when back to ready
                session.last_error = nothing
                session.missed_heartbeats = 0
                session.disconnect_time = nothing

                # Process any pending requests if we just reconnected
                if !isempty(session.pending_requests)
                    @info "Julia session reconnected, processing buffered requests" uuid =
                        uuid name = session.name buffer_size =
                        length(session.pending_requests)
                    @async process_pending_requests(uuid)
                end
            end
        end
    end
end

# ============================================================================
# MCP Session Management
# ============================================================================

"""
    create_mcp_session(target_julia_session_id::Union{String,Nothing}) -> MCPSession

Create a new MCP session for a client connection.

Registers the session in the global registry and logs creation.
"""
function create_mcp_session(target_julia_session_id::Union{String,Nothing})
    session = MCPSession(target_julia_session_id = target_julia_session_id)

    lock(MCP_SESSION_LOCK) do
        MCP_SESSION_REGISTRY[session.id] = session
    end

    @info "Created MCP session" session_id = session.id target_julia_session_id =
        target_julia_session_id
    return session
end

"""
    get_mcp_session(session_id::String) -> Union{MCPSession, Nothing}

Get an MCP session by its ID. Thread-safe.
"""
function get_mcp_session(session_id::String)
    lock(MCP_SESSION_LOCK) do
        return get(MCP_SESSION_REGISTRY, session_id, nothing)
    end
end

"""
    delete_mcp_session!(session_id::String)

Delete an MCP session and clean up resources.
"""
function delete_mcp_session!(session_id::String)
    lock(MCP_SESSION_LOCK) do
        if haskey(MCP_SESSION_REGISTRY, session_id)
            session = MCP_SESSION_REGISTRY[session_id]
            close_session!(session)
            delete!(MCP_SESSION_REGISTRY, session_id)
            @info "Deleted MCP session" session_id = session_id
        end
    end
end

"""
    cleanup_inactive_sessions!(max_age::Dates.Period=Dates.Hour(1))

Remove MCP sessions that haven't been active for longer than max_age.

Useful for periodic cleanup of stale client connections.
"""
function cleanup_inactive_sessions!(max_age::Dates.Period = Dates.Hour(1))
    cutoff = now() - max_age
    lock(MCP_SESSION_LOCK) do
        inactive =
            [id for (id, session) in MCP_SESSION_REGISTRY if session.last_activity < cutoff]
        for id in inactive
            session = MCP_SESSION_REGISTRY[id]
            close_session!(session)
            delete!(MCP_SESSION_REGISTRY, id)
            @info "Cleaned up inactive session" session_id = id
        end
    end
end
